- index.html
- package.json
> Revert "clean up"

- index.html
- src/common.tsx
- src/comparingGenres.tsx
- src/confidenceIntervals.tsx
- src/descriptiveStats.tsx
- src/graphForm.tsx
- src/inferentialStats.tsx
- src/main.css
- src/tabNavigation.tsx
* Add tab navigation component
* Add first version of the graph form
> Add first iteration of the form for the graphs

- src/graphForm.tsx
- src/graphs/distributionHistogram.tsx
- src/graphs/sampleDataHistogram.tsx
- src/graphs/sampleMeanLine.tsx
* Make sure the graphs are receiving the form inputs
* Builds on https://github.com/ccnmtl/statify/pull/26
> Form to graph flow

- src/comparingGenres.tsx
- src/confidenceIntervals.tsx
- src/descriptiveStats.tsx
- src/graphForm.tsx
- src/inferentialStats.tsx
- src/nav.tsx
* implements new changes to the mockup
> mock up changes

- package-lock.json
- package.json
- src/assignments/answer.tsx
- src/assignments/assignment.tsx
- src/assignments/pdfDocument.tsx
- src/common.tsx
- src/inferentialStats.tsx
- src/main.css
Basic implementation of the create pdf functionality.
create pdf based on provided questions and user answers
TODO:
Style pdf
Screenshot functionality
File name
> Assignment section

- src/app.tsx
- src/comparingGenres.tsx
- src/confidenceIntervals.tsx
- src/descriptiveStats.tsx
- src/graphForm.tsx
- src/inferentialStats.tsx
- src/main.css
- src/tabNavigation.tsx
* a couple of formatting changes and div replacements.
> Formatting changes

- src/graphForm.tsx
- src/graphs/histogram.tsx
* small fix to stack the graphs on top of each other
* small change to make the filename lowercase
> graph styling; naming convention

- src/graphs/histogram.tsx
> Reoriented axis labels for histogram

- src/common.tsx
- src/comparingGenres.tsx
- src/confidenceIntervals.tsx
- src/descriptiveStats.tsx
- src/graphForm.tsx
- src/graphs/estimatedSampleDistribution.tsx
- src/graphs/histogram.tsx
- src/inferentialStats.tsx
The `p-value` is commented out for a later update. Otherwise the graph is working as expected.
> Implemented the Estimated Sampling Distribution

- src/globals.d.ts
- src/graphs/estimatedSampleDistribution.tsx
I think I have something close to what they wanted for the p-value. I might need further clarification, otherwise I could ask if this value is necessary given how it seems to just reflect the visual similarity of the two graphs.
> Generate p-value for Estimated Sampling Distribution

- src/common.tsx
- src/graphs/histogram.tsx
Histograms now have hover details
> Added hover details

- src/assignments/answer.tsx
- src/assignments/assignment.tsx
- src/common.tsx
- src/graphForm.tsx
Saving user data in assignment fields
> Stat 40 - Local Storage

- src/graphs/estimatedSampleDistribution.tsx
- src/graphs/histogram.tsx
- src/graphs/sampleMeanLine.tsx
Let me know if there was anything else to do regarding the responsiveness.
> Graphs now resize with browser window

- src/app.tsx
- src/home.tsx
- src/nav.tsx
Adds backslash to paths because it looks better
> add backslash

- package-lock.json
- package.json
> Revert "Bump cypress from 12.17.0 to 13.0.0"

- src/assignments/answer.tsx
- src/assignments/assignment.tsx
I wanted to play around with a possible alternative layout. With the new questions the Answer headers and 'Why? Explain" seemed unnecessary and repetitive. If this conflicts with the current implementation then I understand, but what do you think?
> Alternative Q&A Layout

- src/footer.tsx
- src/graphs/histogram.tsx
- src/main.css
* This needs to be merged so: https://github.com/ccnmtl/statify/pull/137 can pass
> Fix accessibility issues

- src/assignments/assignment.tsx
- src/comparingGenres.tsx
Decided to use `dangerouslySetInnerHTML` so that we could add formatting like `<strong>` and `<em>`
> Instructor Questions for Comparing Genres

- src/confidenceIntervals.tsx
The inset HTML depends on the #151 PR
> Instructor Questions for Confidence Intervals

- src/graphs/estimatedSampleDistribution.tsx
- src/graphs/histogram.tsx
Having these a little more aligned with whats on the shinyapps site. The distribution and sample data graphs had the same title.
> Graph titles

- src/graphs/sampleMeanLine.tsx
This should fix the hover issue
> Render dots after lines

- package-lock.json
> Revert "Bump @sentry/react from 7.67.0 to 7.68.0"

- src/graphs/sampleMeanLine.tsx
I can change the radius size if you think it's too big.
> Line graph dots now have larger hover dots overlayed on top

- src/graphs/sampleMeanLine.tsx
There is still that line artifact issue, but at the very least the resize bug is fixed.
> Fixes resize issue with line graph

- src/main.css
- src/nav.tsx
I refactored the list items into a map function but otherwise this was pretty straight forward.
> The current page is now highlighted on the nav bar

- src/graphs/sampleMeanLine.tsx
> Revert "Adaptable y axis"

- src/graphs/estimatedSampleDistribution.tsx
- src/graphs/histogram.tsx
- src/graphs/sampleMeanLine.tsx
The-p-value overlap is going to be fixed in #190
> Titles adjust position at smaller window sizes

- src/comparingGenres.tsx
- src/confidenceIntervals.tsx
- src/descriptiveStats.tsx
- src/inferentialStats.tsx
- src/main.css
- src/objectiveModal.tsx
- src/tabNavigation.tsx
~~Might conflict with #196~~
Conflicts resolved with #196
> Added a Learning Objectives modal

- src/genrePicker.tsx
> Check if element exists - Sentry

- src/common.tsx
- src/graphForm.tsx
- src/graphs/histogram.tsx
- tests/histogram.test.tsx
This branch is primarily a refactor of the graph generation to reduce overlapping bars and make it easier to render the true desired colors.
The histogram test was removed because there are no more overlapping bins.
> Colors made more accessible

- Jenkinsfile
- src/graphs/estimatedSampleDistribution.tsx
- src/graphs/histogram.tsx
- src/graphs/sampleMeanLine.tsx
A bit of clean up to prevent unnecessary re-renders.
> Remove state listeners

- src/graphs/genrePicker.tsx
- src/main.css
Other adjustments made according to this Jira ticket: https://columbiactl.atlassian.net/browse/STAT-26?filter=10143
> Filter limit checkbox added

- src/graphs/sampleMeanLine.tsx
Gave it a border
Made the opacity so that at a certain point it just doesn't show up.
> make current data more visible

- src/assignments/assignment.tsx
- src/assignments/assignmentDocument.tsx
- src/assignments/imagePreview.tsx
Implemented an ImagePreview for screenshots. Users can now take multiple screenshots
> Can now take multiple screenshots

- src/graphs/graphForm.tsx
So it turns out that I wasn't feeding all of the data in for MeanData2 so the data point was out of range of the graph, but it was being stored in the array.
> Genre 2 Mean Histogram data now appears

- src/assignments/answer.tsx
- src/assignments/assignment.tsx
- src/common.tsx
- src/graphs/estimatedSampleDistribution.tsx
- src/graphs/graphDisplay.tsx
- src/graphs/graphForm.tsx
- src/graphs/histogram.tsx
- src/graphs/sampleMeanLine.tsx
- src/modules/comparingGenres.tsx
- src/modules/confidenceIntervals.tsx
- src/modules/descriptiveStats.tsx
- src/modules/inferentialStats.tsx
All of this was just to have Graph Form as an independent component and keep it in it's own column, but I figured that I would package the variables so it's a little easier to pass them back and forth.
> Refactor: GraphForm is now dependent of GraphDisplay

- src/common.tsx
- src/graphs/graphDisplay.tsx
- src/graphs/graphForm.tsx
- src/graphs/sampleMeanLine.tsx
- src/graphs/utils.tsx
- src/modules/comparingGenres.tsx
- src/modules/confidenceIntervals.tsx
- src/modules/descriptiveStats.tsx
- src/modules/inferentialStats.tsx
This required a bit of a refactor for the line graph, but I tried to maintain as close to the original structure as I could. Running on a brand new Mac I didn't experience any slow down but that might not be the case for older devices, especially on moblie.
Closes #195
> Y-axis on the line graph now adapts to datapoints

- package-lock.json
> Revert "Bump @typescript-eslint/eslint-plugin from 8.38.0 to 8.39.0"
